---
version: 2

build:
  os: ubuntu-lts-latest
  apt_packages:
    - krb5-multidev
    - libclang-dev
    - libkrb5-dev
    - pkg-config
  tools:
    python: "latest"
    rust: "latest"
  jobs:
    post_checkout:
      - sed '/rustc-wrapper/d' .cargo/config.toml

python:
  install:
    - method: pip
      path: .

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  builder: html
  configuration: python-kadmin-rs/docs/conf.py
  fail_on_warning: true

formats: all
