---
version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - build-essential
    - pkg-config
    - krb5-multidev
    - libkrb5-dev
    - heimdal-multidev
    - libclang-dev
    - python3-dev
  tools:
    python: "latest"
    rust: "latest"

python:
  install:
    - requirements: python/docs/requirements.txt
    - method: pip
      path: .

# Build documentation in the "python/docs/" directory with Sphinx
sphinx:
  builder: html
  configuration: python/docs/conf.py
  fail_on_warning: true
