---
name: Create release PR

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        required: true
        type: choice
        options:
          - kadmin
      version:
        description: Version to release
        required: true
        type: string

env:
  DEBIAN_FRONTEND: noninteractive
  CARGO_INCREMENTAL: "false"

jobs:
  release-pr:
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: chainguard-dev/actions/setup-gitsign@3b7bbeebc3a5d2bc37aa008350202651c32a26e1 # main
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      - uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: just,cargo-release,cargo-workspaces
      - run: just ci-build-deps
      - uses: cargo-bins/release-pr@0c019c0e5a6b9f722578d231d43ba900cacc5ffa # v2.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          crate-name: ${{ inputs.package }}
          pr-label: release
